apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cms
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: catalog
spec:
  project: default
  source:
    repoURL: git@github.com:TheApeMachine/catalog.git
    targetRevision: release
    path: .kube
  destination:
    server: https://kubernetes.default.svc
    namespace: release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
