apiVersion: v1
kind: Secret
metadata:
  name: a2a-go-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:TheApeMachine/a2a-go.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"
