# Server configuration
server:
  host: "localhost"
  port: 3210
  defaultRPCPath: "/rpc"
  defaultSSEPath: "/events"

# Agent configuration
agent:
  name: "Echo Agent"
  version: "0.1.0"
  capabilities:
    streaming: true
    pushNotifications: true
    stateTransitionHistory: true

# OpenAI configuration
openai:
  apiKey: "" # Set via environment variable or command line flag

# MCP configuration
mcp:
  embedded_agent: false
