provider:
  openai:
    model: "gpt-4o-mini"
    embed: "text-embedding-3-large"

server:
  host: "localhost"
  port: 3210
  defaultRPCPath: "/rpc"
  defaultSSEPath: "/events"

endpoints:
  browsertool: "http://browsertool:3210"
  dockertool: "http://dockertool:3210"
  catalogtool: "http://catalogtool:3210"
  azure_get_sprintstool: "http://azure_get_sprints:3210"
  azure_create_sprinttool: "http://azure_create_sprint:3210"
  azure_sprint_itemstool: "http://azure_sprint_items:3210"
  azure_sprint_overviewtool: "http://azure_sprint_overview:3210"
  azure_get_work_itemstool: "http://azure_get_work_items:3210"
  azure_create_work_itemstool: "http://azure_create_work_items:3210"
  azure_update_work_itemstool: "http://azure_update_work_items:3210"
  azure_execute_wiqlt: "http://azure_execute_wiql:3210"
  azure_search_work_itemstool: "http://azure_search_work_items:3210"
  azure_enrich_work_itemtool: "http://azure_enrich_work_item:3210"
  azure_get_github_file_contenttool: "http://azure_get_github_file_content:3210"
  azure_work_item_commentstool: "http://azure_work_item_comments:3210"
  azure_find_items_by_statustool: "http://azure_find_items_by_status:3210"
  catalog: "http://catalog:3210"
  catalogPath: "/.well-known/catalog.json"

agent:
  ui:
    name: "User Interface Agent"
    version: "0.1.0"
    protocol: "0.2.6"
    iconUrl: "https://theapemachine.org/icons/ui.png"
    url: "http://ui:3210"
    provider:
      organization: "The Ape Machine"
      url: "https://theapemachine.org"
    documentationUrl: "https://theapemachine.org/docs/ui"
    capabilities:
      streaming: true
      pushNotifications: true
      stateTransitionHistory: true
    authentication:
      schemes:
      - "bearer"
      - "basic"
      credentials: "****"
    system:
    - You are an advanced AI agent, performing in the role of user interface.
    - You are talking directly to the user, and you must relay the message from the user
    - to a relevant agent. You must also relay the response from the agent back to the user.
    - You should never try to directly respond to the user's request, only relay messages.
    skills:
    - communication
    - catalog
    - management
  manager:
    name: "Manager Agent"
    version: "0.1.0"
    protocol: "0.2.6"
    iconUrl: "https://theapemachine.org/icons/manager.png"
    url: "http://manager:3210"
    provider:
      organization: "The Ape Machine"
      url: "https://theapemachine.org"
    documentationUrl: "https://theapemachine.org/docs/manager"
    capabilities:
      streaming: true
      pushNotifications: true
      stateTransitionHistory: true
    authentication:
      schemes:
      - "bearer"
      - "basic"
      credentials: "****"
    system:
    - You are an advanced AI agent, performing in the role of manager.
    - You are able to delegate tasks to other agents, and track their progress.
    - You are able to review the work of other agents, and provide feedback.
    skills:
    - management
  planner:
    name: "Planner Agent"
    version: "0.1.0"
    protocol: "0.2.6"
    iconUrl: "https://theapemachine.org/icons/planner.png"
    url: "http://planner:3210"
    provider:
      organization: "The Ape Machine"
      url: "https://theapemachine.org"
    documentationUrl: "https://theapemachine.org/docs/planner"
    capabilities:
      streaming: true
      pushNotifications: true
      stateTransitionHistory: true
    authentication:
      schemes:
      - "bearer"
      - "basic"
      credentials: "****"
    system:
    - You are an advanced AI agent, performing in the role of planner.
    - You are able to plan tasks, or compositions of tasks.
    - You are able to track the progress of tasks, and provide feedback.
    skills:
    - planning
  researcher:
    name: "Researcher Agent"
    version: "0.1.0"
    protocol: "0.2.6"
    iconUrl: "https://theapemachine.org/icons/researcher.png"
    url: "http://researcher:3210"
    provider:
      organization: "The Ape Machine"
      url: "https://theapemachine.org"
    documentationUrl: "https://theapemachine.org/docs/researcher"
    capabilities:
      streaming: true
      pushNotifications: true
      stateTransitionHistory: true
    authentication:
      schemes:
      - "bearer"
      - "basic"
      credentials: "****"
    system:
    - You are an advanced AI agent, performing in the role of researcher.
    - You are able to research information, and provide feedback.
    skills:
    - web-browsing
  developer:
    name: "Developer Agent"
    version: "0.1.0"
    protocol: "0.2.6"
    iconUrl: "https://theapemachine.org/icons/developer.png"
    url: "http://developer:3210"
    provider:
      organization: "The Ape Machine"
      url: "https://theapemachine.org"
    documentationUrl: "https://theapemachine.org/docs/developer"
    capabilities:
      streaming: true
      pushNotifications: true
      stateTransitionHistory: true
    authentication:
      schemes:
      - "bearer"
      - "basic"
      credentials: "****"
    system:
    - You are an advanced AI agent, performing in the role of developer.
    - You are able to develop software, and provide feedback.
    skills:
    - development
  evaluator:
    name: "Evaluator Agent"
    version: "0.1.0"
    protocol: "0.2.6"
    iconUrl: "https://theapemachine.org/icons/evaluator.png"
    url: "http://evaluator:3210"
    provider:
      organization: "The Ape Machine"
      url: "https://theapemachine.org"
    documentationUrl: "https://theapemachine.org/docs/evaluator"
    capabilities:
      streaming: true
      pushNotifications: true
      stateTransitionHistory: true
    authentication:
      schemes:
      - "bearer"
      - "basic"
      credentials: "****"
    system:
    - You are an advanced AI agent, performing in the role of evaluator.
    - You evaluate whether task outputs meet completion requirements.
    - You receive the original task and an agent's output, then judge if it's complete.
    - Respond with exactly - DECISION:[COMPLETE/ITERATE/ESCALATE] REASONING:[explanation]
    - COMPLETE means task is fully satisfied. ITERATE means try again. ESCALATE means different approach needed.
    - Be thorough but practical in your evaluation.
    - Consider if the output directly addresses what was requested.
    - Judge completeness, accuracy, and usefulness of results.
    skills:
    - evaluation

mcp:
  embedded_agent: false

tools:
  builder:
    name: "editor"
    description: |
      A tool which is specialized towards editing source code.
    params:
    - name: "filename"
      description: "The filename to edit."
      required: false
    - name: "find"
      description: "A sub-string to search for within the source code."
      required: false
    - name: "replace"
      description: "The string to replace the find string with."
      required: false
    - name: "from"
      description: "The line number to start editing from."
      required: false
    - name: "to"
      description: "The line number to stop editing at."
      required: false
    - name: "content"
      description: "The content to insert between the from and to line numbers."
      required: false

skills:
  communication:
    id: "communication"
    name: "communication"
    description: "Communication with the user."
    tags:
    - "communication"
    - "user"
    examples:
    - "Relay the message from the user to the agent."
    - "Relay the response from the agent to the user."
    input_modes:
    - "text/plain"
    output_modes:
    - "text/plain"
  planning:
    id: "planning"
    name: "planning"
    description: "Planning of tasks."
    tags:
    - "planning"
    - "task"
    examples:
    - "Plan the tasks for the day."
    - "Develop a plan for the project."
    input_modes:
    - "text/plain"
    output_modes:
    - "text/plain"
  web-browsing:
    id: "web-browsing"
    name: "web-browsing"
    description: "Browsing the web."
    tags:
    - "web-browsing"
    - "web"
    examples:
    - "Search for the latest news on the web."
    - "Find the latest information on the provided topic."
    input_modes:
    - "text/plain"
    output_modes:
    - "text/plain"
  management:
    id: "management"
    name: "management"
    description: "Management of tasks and agents."
    tags:
    - "management"
    - "task"
    examples:
    - "Delegate the task to the developer agent."
    - "Review the work of the developer agent."
    input_modes:
    - "text/plain"
    output_modes:
    - "text/plain"
  development:
    id: "development"
    name: "development"
    description: "Development of code."
    tags:
    - "development"
    - "code"
    - "Develop a web-service which interfaces with MongoDB."
    examples:
    - "Develop a web-service which interfaces with MongoDB."
    input_modes:
    - "text/plain"
    output_modes:
    - "text/plain"
  evaluation:
    id: "evaluation"
    name: "evaluation"
    description: "Evaluation of task completion quality."
    tags:
    - "evaluation"
    - "quality"
    - "completion"
    examples:
    - "Evaluate if a task output meets the original requirements."
    - "Judge whether a response is complete and satisfactory."
    input_modes:
    - "text/plain"
    output_modes:
    - "text/plain"
  penetration-testing:
    id: "penetration-testing"
    name: "penetration-testing"
    description: "Evaluate the security of code and services."
    tags:
    - "penetration-testing"
    - "security"
    examples:
    - "Test the security of the provided server."
    - "Identify the vulnerabilities in the provided code."
    - "Test the code for SQL injection vulnerabilities."
    input_modes:
    - "text/plain"
    output_modes:
    - "text/plain"
  catalog:
    id: "catalog"
    name: "catalog"
    description: "Inspect the catalog and list available agents and tasks."
    tags:
    - "catalog"
    - "agents"
    examples:
    - "List all available agents."
    input_modes:
    - "text/plain"
    output_modes:
    - "text/plain"
