provider:
  openai:
    model: "gpt-4o-mini"
    embed: "text-embedding-3-large"

server:
  host: "localhost"
  port: 3210
  defaultRPCPath: "/rpc"
  defaultSSEPath: "/events"
  defaultCatalogPath: "/.well-known/catalog.json"
  catalog: "http://catalog:3210"

agent:
  ui:
    name: "User Interface Agent"
    version: "0.1.0"
    url: "http://ui:3210"
    provider:
      organization: "The Ape Machine"
      url: "https://theapemachine.org"
    documentationUrl: "https://theapemachine.org/docs/ui"
    capabilities:
      streaming: true
      pushNotifications: true
      stateTransitionHistory: true
    authentication:
      schemes:
        - "bearer"
        - "basic"
      credentials: "****"
    system:
      - You are an advanced AI agent, performing in the role of user interface.
      - You are talking directly to the user, and you must relay the message from the user
      - to a relevant agent. You must also relay the response from the agent back to the user.
      - You should never try to directly respond to the user's request, only relay messages.
    skills:
      - communication
  manager:
    name: "Manager Agent"
    version: "0.1.0"
    url: "http://manager:3210"
    provider:
      organization: "The Ape Machine"
      url: "https://theapemachine.org"
    documentationUrl: "https://theapemachine.org/docs/manager"
    capabilities:
      streaming: true
      pushNotifications: true
      stateTransitionHistory: true
    authentication:
      schemes:
        - "bearer"
        - "basic"
      credentials: "****"
    system:
      - You are an advanced AI agent, performing in the role of manager.
      - You are able to delegate tasks to other agents, and track their progress.
      - You are able to review the work of other agents, and provide feedback.
    skills:
      - management
  planner:
    name: "Planner Agent"
    version: "0.1.0"
    url: "http://planner:3210"
    provider:
      organization: "The Ape Machine"
      url: "https://theapemachine.org"
    documentationUrl: "https://theapemachine.org/docs/planner"
    capabilities:
      streaming: true
      pushNotifications: true
      stateTransitionHistory: true
    authentication:
      schemes:
        - "bearer"
        - "basic"
      credentials: "****"
    system:
      - You are an advanced AI agent, performing in the role of planner.
      - You are able to plan tasks, or compositions of tasks.
      - You are able to track the progress of tasks, and provide feedback.
    skills:
      - planning
  researcher:
    name: "Researcher Agent"
    version: "0.1.0"
    url: "http://researcher:3210"
    provider:
      organization: "The Ape Machine"
      url: "https://theapemachine.org"
    documentationUrl: "https://theapemachine.org/docs/researcher"
    capabilities:
      streaming: true
      pushNotifications: true
      stateTransitionHistory: true
    authentication:
      schemes:
        - "bearer"
        - "basic"
      credentials: "****"
    system:
      - You are an advanced AI agent, performing in the role of researcher.
      - You are able to research information, and provide feedback.
    skills:
      - web-browsing
  developer:
    name: "Developer Agent"
    version: "0.1.0"
    url: "http://developer:3210"
    provider:
      organization: "The Ape Machine"
      url: "https://theapemachine.org"
    documentationUrl: "https://theapemachine.org/docs/developer"
    capabilities:
      streaming: true
      pushNotifications: true
      stateTransitionHistory: true
    authentication:
      schemes:
        - "bearer"
        - "basic"
      credentials: "****"
    system: |
      You are an advanced AI agent, performing in the role of developer.
      You are able to develop code, and interact with other agents.
      Each time you receive a task, you will be placed in an iteration loop.
      To exit the loop, and mark you task as complete, just respond with "task complete".
    skills:
      - development

mcp:
  embedded_agent: false

skills:
  communication:
    id: "communication"
    name: "communication"
    description: "Communication with the user."
    tags:
      - "communication"
      - "user"
    examples:
      - "Relay the message from the user to the agent."
      - "Relay the response from the agent to the user."
    input_modes:
      - "text/plain"
    output_modes:
      - "text/plain"
  planning:
    id: "planning"
    name: "planning"
    description: "Planning of tasks."
    tags:
      - "planning"
      - "task"
    examples:
      - "Plan the tasks for the day."
      - "Develop a plan for the project."
    input_modes:
      - "text/plain"
    output_modes:
      - "text/plain"
  web-browsing:
    id: "web-browsing"
    name: "web-browsing"
    description: "Browsing the web."
    tags:
      - "web-browsing"
      - "web"
    examples:
      - "Search for the latest news on the web."
      - "Find the latest information on the provided topic."
    input_modes:
      - "text/plain"
    output_modes:
      - "text/plain"
  management:
    id: "management"
    name: "management"
    description: "Management of tasks and agents."
    tags:
      - "management"
      - "task"
    examples:
      - "Delegate the task to the developer agent."
      - "Review the work of the developer agent."
    input_modes:
      - "text/plain"
    output_modes:
      - "text/plain"
  development:
    id: "development"
    name: "development"
    description: "Development of code."
    tags:
      - "development"
      - "code"
      - "Develop a web-service which interfaces with MongoDB."
    input_modes:
      - "text/plain"
    output_modes:
      - "text/plain"
  penetration-testing:
    id: "penetration-testing"
    name: "penetration-testing"
    description: "Evaluate the security of code and services."
    tags:
      - "penetration-testing"
      - "security"
    examples:
      - "Test the security of the provided server."
      - "Identify the vulnerabilities in the provided code."
      - "Test the code for SQL injection vulnerabilities."
    input_modes:
      - "text/plain"
    output_modes:
      - "text/plain"
