provider:
  openai:
    model: "gpt-4o-mini"
    embed: "text-embedding-3-large"

server:
  host: "localhost"
  port: 3210
  defaultRPCPath: "/rpc"
  defaultSSEPath: "/events"
  defaultCatalogPath: "/.well-known/catalog.json"
  catalogServer:
    host: "${CATALOG_URL:http://catalog:3210}"

agent:
  manager:
    name: "Manager Agent"
    version: "0.1.0"
    url: "http://localhost:4321"
    capabilities:
      streaming: true
      pushNotifications: true
      stateTransitionHistory: true
    system:
      - You are an advanced AI agent, performing in the role of manager.
      - You are able to delegate tasks to other agents, and track their progress.
      - You are able to review the work of other agents, and provide feedback.
    skills:
      - planning
  developer:
    name: "Developer Agent"
    version: "0.1.0"
    url: "http://localhost:4322"
    capabilities:
      streaming: true
      pushNotifications: true
      stateTransitionHistory: true
    system: |
      You are an advanced AI agent, performing in the role of developer.
      You are able to develop code, and interact with other agents.
      Each time you receive a task, you will be placed in an iteration loop.
      To exit the loop, and mark you task as complete, just respond with "task complete".
    skills:
      - development

mcp:
  embedded_agent: false

skills:
  planning:
    id: "planning"
    name: "planning"
    description: "Planning of tasks."
    tags:
      - "planning"
      - "task"
    examples:
      - "Plan the tasks for the day."
      - "Develop a plan for the project."
    input_modes:
      - "text/plain"
    output_modes:
      - "text/plain"
  development:
    id: "development"
    name: "development"
    description: "Development of code."
    tags:
      - "development"
      - "code"
      - "Develop a web-service which interfaces with MongoDB."
    input_modes:
      - "text/plain"
    output_modes:
      - "text/plain"
  penetration-testing:
    id: "penetration-testing"
    name: "penetration-testing"
    description: "Evaluate the security of code and services."
    tags:
      - "penetration-testing"
      - "security"
    examples:
      - "Test the security of the provided server."
      - "Identify the vulnerabilities in the provided code."
      - "Test the code for SQL injection vulnerabilities."
    input_modes:
      - "text/plain"
    output_modes:
      - "text/plain"
