{{- if .SecretName -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .SecretName }}
type: Opaque
stringData:
  {{- range $key, $value := .SecretData }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end -}} 