---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}
  labels:
    app: {{ .Name }}
spec:
  ports:
    - name: http
      port: {{ .Port }}
      targetPort: {{ .Port }}
  selector:
    app: {{ .Name }}
  type: ClusterIP 