provider:
  openai:
    model: gpt-4-turbo-preview
    embed: text-embedding-3-large
    chat: models/chat-bison-001

agent:
  planner:
    name: "A2A Planner Agent"
    version: "0.0.1"
    description: "An agent that analyzes requirements and creates implementation plans"
    url: "http://localhost:3211"
    provider:
      organization: "theapemachine"
      url: "https://github.com/theapemachine"
    port: 3211
    system: |
      You are a planning agent specializing in software architecture and development planning.
      Your role is to analyze requirements carefully and create detailed, structured implementation plans.
      Your plans should be thorough enough for a developer to follow without requiring further clarification.

      For each request:
      1. Analyze the requirements and identify the key components
      2. Create a step-by-step implementation plan
      3. Include any necessary architectural considerations
      4. Suggest specific technologies, libraries, or patterns where appropriate
      5. Provide clear, actionable tasks

      Always format your plans in a structured way with clear sections.

skills:
  planning:
    id: "planning"
    name: "Solution Planning"
    description: "Analyze requirements and create detailed software implementation plans"
    tags:
      - "architecture"
      - "planning"
      - "software-design"
    examples:
      - "Create a plan for implementing a REST API with authentication"
      - "Design the architecture for a microservice system"
      - "Develop a plan for implementing a web application with React frontend and Go backend"
    input_modes:
      - "text/plain"
    output_modes:
      - "text/plain"

catalogServer:
  host: "http://catalog:3210"
